### ISSUE TITLE
What was the method using for getting the OCR-text ground-truth 

### ISSUE THREAD

**Issue by anhhaibkhn** [apismensky/ocr_id#1]
Hi @apismensky  Alexey,
Hope you are doing well. 

My apology for opening a discussion here, as I did not see any updates on your question in the Tesseract-ocr groups.

As I went through your code, I could not help but there was a file "{image_name}".txt (ex: black.txt )  which was used for the calculate_word_accuracy method. May I ask what was the method to get this result?

Aside from that, since our last discussion, I have tried CRAFT to extract the crop images, and then I passed them to Tesseract. However, I noticed that several characters in some of the cropped images actually bend from their original shapes. 
CRAFT cropped image:
![image](https://github.com/apismensky/ocr_id/assets/30589132/2c4e8de8-3bf1-4f58-818c-c1e388754bdc)
ORG shape:
![image](https://github.com/apismensky/ocr_id/assets/30589132/96e69260-e370-4938-b4c0-1417d399683c)
My guess is that when the CRAFT detect_text method cropped the image, it tried to fix curvy text lines:
![image](https://github.com/apismensky/ocr_id/assets/30589132/9d235046-f739-4853-b38c-0fe1e2606e09)
I could take the .uzn data, and crop them out again, but that would take more processing time. I hope to hear your suggestion on this matter.

Thank you for your time. 
Hai

**Comment by anhhaibkhn** [comment]
I have just some other comments about the CRAFT algorithm, sometimes the text detection part method was slightly incorrect. In the following example, it merged some text regions together, which later yielded unsatisfied OCR results from Tesseract. Perhaps, there is some merging gap threshold that could be modified to improve this behavior. 
Ex: 
![image](https://github.com/apismensky/ocr_id/assets/30589132/1ce2571d-e2fa-43c1-9711-5ad12bbfdb19)

**Comment by apismensky** [comment]
> calculate_word_accuracy

Hi @anhhaibkhn , sorry for late response (I was swamped with some work)
To get the ground truth I just manually created a text file. I think I've passed it to Google Cloud Vision demo at https://cloud.google.com/vision 
calculate_word_accuracy is to calculate word accuracy of OCR, based on the words that recognized correctly. 
Roughly, it is a (number of words detected correctly / total number of words) * 100% 

The ground truth text is provided as a second parameter to the function. 
I've seen that some folks are using "levenshtein distance" to evaluate accuracy. 
Are there better solutions to calculate accuracy?

**Comment by apismensky** [comment]
> some of the cropped images actually bend from their original shapes

Did you check CRAFT settings / API to see if this can be disabled/enabled? 
It might make sense for CRAFT to have that feature for some skewed/angled images, so it is not surprising. 
If you know for sure that you only have scanned documents or screen captures it would make sense to disable that. 
But IDK the answer off the top of my head

**Comment by apismensky** [comment]
> it merged some text regions together, which later yielded unsatisfied OCR results from Tesseract

Not really sure, but what I've seen before for tesseract - it fails to OCR if you have inverted color schemes within the same image (as in your example - black on white + white on black). Why did you decide to merge the regions and how did you do that?

**Comment by anhhaibkhn** [comment]
Thank you for your reply. 
I think the calculate_word_accuracy method is good enough for getting the general accuracy. Levenshtein distance is also a good choice, we use it for OCR post-processing, which aims to fix certain text fields in case of OCR errors. I did not implement any method to measure the general accuracy of my current project. (which I realized now, I should do). I have a certain set of sample images and some users checked only certain fields of text. 

I was curious since I saw your .txt files which have the perfect OCR results. Thank you for clearing that out. 

> Why did you decide to merge the regions and how did you do that?
I did not merge them on purpose, I tested CRAFT on a set of black-background text mixed samples. and the prediction boxes of text got merged sometimes (as in the above pic). I guess it is due to the unstable quality of scanned images. 

>It might make sense for CRAFT to have that feature for some skewed/angled images, so it is not surprising.

I checked their source code, which turned out to be simpler than I thought. just change the parameter from 'poly' to 'box', it will give the original cropped images. 

Aside from the above matter, I managed to run CRAFT with GPU on my local windows, where I can see the much faster detection results. The 1st time of inference usually takes the longest around 2-3 seconds, which is understandable since it has to load the model to GPU. After that, each sample took less than 0.6 seconds (on average) for text detection. However, the GPU-running version of CRAFT only works with Python 3.10. I wonder if you may have acknowledged any other text detection method and their performance.
